name: Deploy-Serverless

on: push

jobs:
  example-job:
    
    env:
      FAAS_PROVIDER: aws
      MAVEN_SERVER_ID: github-packages # this is the id set in pom.xml

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK and Maven settings
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ${{ env.MAVEN_SERVER_ID }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Package
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        uses: axel-op/package-java-agnostic-serverless-function@main
        with:
          function-name: name-of-your-function
          faas-provider: ${{ env.FAAS_PROVIDER }}
        # working-directory: . # required if different from $GITHUB_WORKSPACE
